### ISSUE TITLE
Version 0.1.4 crashes on import

### ISSUE THREAD

**Issue by micahflee** [keybase/pykeybasebot#14]
When I run `import pykeybasebot`, I get this error:

```
$ python3
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykeybasebot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pykeybasebot/__init__.py", line 1, in <module>
    from .bot import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pykeybasebot/bot.py", line 8, in <module>
    from .chat_client import ChatClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pykeybasebot/chat_client.py", line 3, in <module>
    from .types import chat1
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pykeybasebot/types/chat1/__init__.py", line 20, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
>>> 
```

This didn't happen in version 0.1.1.

**Comment by nathunsmitty** [comment]
Thanks for reporting @micahflee! We recently started to incorporate type annotations into the python bot – I had assumed `typing_extensions` was part of the stdlib, but I guess it isn't. I'll add it as an explicit dependency, that should hopefully fix the issue.
