### ISSUE TITLE
Exception: Logged in as  instead of [username]. Please logout first

### ISSUE THREAD

**Issue by micahflee** [keybase/pykeybasebot#19]
I'm trying to port my code from pykeybasebot 0.1.1 to 0.1.5 and running into a strange exception. First, I set the environment variables:

```sh
export KEYBASE_USERNAME=my_username
export KEYBASE_PAPERKEY="insert paperkey here"
```

Then I open a python interpreter and copy and paste this very simple script:

```python
import os
import asyncio
import pykeybasebot

class Handler:
    async def __call__(self, bot, event):
        print(event)

bot = pykeybasebot.Bot(
    username=os.environ.get("KEYBASE_USERNAME"),
    paperkey=os.environ.get("KEYBASE_PAPERKEY"),
    handler=Handler()
)

async def main():
    await bot.start({
        "local": False,
        "wallet": False,
        "dev": False,
        "hide-exploding": False,
        "filter_channels": None,
        "filter_channel": None
    })

asyncio.run(main())
```

I'm running this in a `python:3.7.4-buster` docker container with keybase installed via the instructions at https://keybase.io/docs/the_app/install_linux. So inside the container, I'm not logged into any keybase account.

When I try running it, it throws this exception:

```
>>> asyncio.run(main())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "<stdin>", line 8, in main
  File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pykeybasebot/bot.py", line 24, in wrapped_f
    await keybase_bot_start_function(self, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pykeybasebot/bot.py", line 87, in start
    async with _botlifecycle(self, listen_options) as events:
  File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pykeybasebot/bot.py", line 54, in __aenter__
    await self.bot.ensure_initialized()
  File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pykeybasebot/bot.py", line 113, in ensure_initialized
    if not await self._is_initialized():
  File "/home/user/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pykeybasebot/bot.py", line 132, in _is_initialized
    f"Logged in as {actual_username} instead of {self.username}. Please logout first"
Exception: Logged in as  instead of my_username. Please logout first
>>> 
```

But I'm not logged in at all:

```
$ keybase status
Username:      
Logged in:     no
Session:
    is valid:  no
    keys:      locked

Key status:
    stream:    not cached
    secret:    not stored
    dev sig:   not cached
    dev enc:   not cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached
[...snip...]
```

**Comment by maxtaco** [comment]
Sorry for the bug. Looks actually like somehow you are the `""` user, or some such. There must be at least one or two bugs at play, but hopefully we can figure them out quickly.

cc @xgess and @pzduniak

**Comment by xgess** [comment]
hey @micahflee do you mind shooting me over your dockerfile? i guess either here or `@xgess` on keybase? i have a thought though. might not be able to get into it until the morning. 
and sorry it's not working.

**Comment by xgess** [comment]
@micahflee pretty sure i duped and fixed your issue here: https://github.com/keybase/pykeybasebot/pull/20

**Comment by micahflee** [comment]
Ooh excellent. I know it's late but FYI here's my Dockerfile: https://github.com/firstlookmedia/flock/blob/master/src/Dockerfile

I'll test 0.1.6 and let you know if it seems solved for me.

**Comment by micahflee** [comment]
Confirmed this fixed the problem! Thanks.
