### ISSUE TITLE
ValueError: I/O operation on closed pipe when i recieve message

### ISSUE THREAD

**Issue by dnorhoj** [keybase/pykeybasebot#33]
I get the error below when I receive a message after I run the script.

OS: Windows 10
Python version: 3.8.0

## My code:
```py
import asyncio
import pykeybasebot

def handler(bot,event):
	print(event)

bot = pykeybasebot.Bot(handler=handler, username="xxxx")

listen_options = {
	"local": True,
	"wallet": True,
	"dev": True,
	"hide-exploding": False,
	"filter_channel": None,
	"filter_channels": None,
}

asyncio.run(bot.start(listen_options))
```

## Error

```
ERROR:root:Unable to decode JSON output: Listening for chat notifications. Config: hideExploding: false, showLocal: true, subscribeDevChannels: true
ERROR:root:Unable to decode JSON output: Listening for wallet notifications
Traceback (most recent call last):
  File ".\test.py", line 12, in <module>
    bot.run()
  File "C:\Users\dnorh\OneDrive\Projects\Python\OOP\keybase_bot\keybase\bot.py", line 37, in run
    asyncio.run(self.bot.start(listen_options))
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\site-packages\pykeybasebot\bot.py", line 23, in wrapped_f
    await keybase_bot_start_function(self, *args, **kwargs)
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\site-packages\pykeybasebot\bot.py", line 91, in start
    asyncio.create_task(self.handler(self, event))
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 382, in create_task
    task = loop.create_task(coro)
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 427, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000027FA991BA60>
Traceback (most recent call last):
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027FA993D160>
Traceback (most recent call last):
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\dnorh\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by dnorhoj** [comment]
I found the issue.

The handler function wasn't a coroutine
