### ISSUE TITLE
Not compatible with python 3.9

### ISSUE THREAD

**Issue by JustDevZero** [keybase/pykeybasebot#61]
If i try to install pykeybasebot on python3.9, even pip doesn't argue against and installs it succesfully it looks like part of the code is not yet compatible:

```

kbot    | Traceback (most recent call last):
kbot    |   File "/home/keybase/project/kbot.py", line 474, in <module>
kbot    |     pingbot.run()
kbot    |   File "/home/keybase/project/kbot.py", line 78, in run
kbot    |     asyncio.run(self._bot.start(listen_options))
kbot    |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
kbot    |     return loop.run_until_complete(main)
kbot    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
kbot    |     return future.result()
kbot    |   File "/home/keybase/virtualenv/lib/python3.9/site-packages/pykeybasebot/bot.py", line 25, in wrapped_f
kbot    |     await keybase_bot_start_function(self, *args, **kwargs)
kbot    |   File "/home/keybase/virtualenv/lib/python3.9/site-packages/pykeybasebot/bot.py", line 93, in start
kbot    |     async for event in events:
kbot    |   File "/home/keybase/virtualenv/lib/python3.9/site-packages/pykeybasebot/cli.py", line 53, in kblisten
kbot    |     yield KbEvent.from_json(decoded_line)
kbot    |   File "/home/keybase/virtualenv/lib/python3.9/site-packages/dataclasses_json/api.py", line 135, in from_json
kbot    |     kvs = json.loads(s,
kbot    |   File "/usr/local/lib/python3.9/json/__init__.py", line 359, in loads
kbot    |     return cls(**kw).decode(s)
kbot    | TypeError: __init__() got an unexpected keyword argument 'encoding'

```

That appears to be, because encoding keyword has been removed from python3.9:
https://docs.python.org/3/library/json.html#json.loads

**Comment by DeastinY** [comment]
That fixed it for me, thanks!
